# Generated by Django 5.2.3 on 2025-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequest',
            name='is_day_off',
            field=models.BooleanField(default=False),
        ),
    ]
