# Generated by Django 5.1.6 on 2025-06-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shift_usershift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='max_people',
        ),
    ]
