# Generated by Django 5.2.3 on 2025-06-30 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_shift_max_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershift',
            name='shift_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftpattern'),
        ),
    ]
