# Generated by Django 5.2.3 on 2025-06-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
        ('shifts', '0007_usershift_shift_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershift',
            name='shift_pattern',
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('date', 'team', 'pattern')},
        ),
    ]
