# Generated by Django 5.2.3 on 2025-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_remove_usershift_shift_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_rest',
            field=models.BooleanField(default=False),
        ),
    ]
