# Generated by Django 5.2.3 on 2025-07-12 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
        ('shifts', '0012_remove_shift_is_rest_shiftpattern_is_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpattern',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
        ),
    ]
