# Generated by Django 5.1.6 on 2025-07-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
        ('shifts', '0013_shiftpattern_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftpattern',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
            preserve_default=False,
        ),
    ]
