# Generated by Django 5.1.6 on 2025-07-15 13:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0014_alter_shiftpattern_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usershift',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usershift',
            name='date',
            field=models.DateField(default=datetime.date(2025, 7, 15)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usershift',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shift'),
        ),
        migrations.AddConstraint(
           model_name='usershift',
          constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
    ]
