# Generated by Django 5.1.6 on 2025-07-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_alter_usershift_unique_together_usershift_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershift',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
